apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: history-db
spec:
  serviceName: "history-db"
  replicas: 1
  selector:
    matchLabels:
      app: history-db
  template:
    metadata:
      labels:
        app: history-db
    spec:
      containers:
      - name: history-db
        image: mongodb/mongodb-atlas-local
        ports:
        - containerPort: 27017  # Default MongoDB port
