apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: question-db
spec:
  serviceName: "question-db"
  replicas: 1
  selector:
    matchLabels:
      app: question-db
  template:
    metadata:
      labels:
        app: question-db
    spec:
      containers:
      - name: question-db
        image: mongodb/mongodb-atlas-local
        ports:
        - containerPort: 27017  # Default MongoDB port
