apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - name: question-service
        image: wuemily/question-service:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: PORT
          value: "3001"
        envFrom:
            - configMapRef:
                name: app-config